apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: {{ .Values.notification.replicaCount }}
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification
          image: {{ .Values.notification.image }}
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: market-config
                  key: DB_URL
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: market-config
                  key: DB_SCHEMA
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: market-config
                  key: KAFKA_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: market-config-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: market-config-secret
                  key: DB_PASS
          ports:
            - containerPort: {{ .Values.notification.service.port }}
              name: web
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification-app
  ports:
    - protocol: TCP
      port: {{ .Values.notification.service.port }}
      targetPort: web
      name: web
  type: {{ .Values.notification.service.type }}

